"use client";

import { useState } from "react";

export default function Home() {
  const [message, setMessage] = useState("");
    const [reply, setReply] = useState("");
      const [loading, setLoading] = useState(false);

        async function sendMessage() {
            if (!message.trim() || loading) return;

                setLoading(true);
                    setReply("");

                        try {
                              const response = await fetch("/api/chat", {
                                      method: "POST",
                                              headers: {
                                                        "Content-Type": "application/json",
                                                                },
                                                                        body: JSON.stringify({ message }),
                                                                              });

                                                                                    const data = await response.json();

                                                                                          if (!response.ok) {
                                                                                                  throw new Error(data.error || "Terjadi kesalahan.");
                                                                                                        }

                                                                                                              setReply(data.reply);
                                                                                                                  } catch (error) {
                                                                                                                        setReply(
                                                                                                                                error instanceof Error
                                                                                                                                          ? error.message
                                                                                                                                                    : "Terjadi kesalahan."
                                                                                                                                                          );
                                                                                                                                                              } finally {
                                                                                                                                                                    setLoading(false);
                                                                                                                                                                        }
                                                                                                                                                                          }

                                                                                                                                                                            return (
                                                                                                                                                                                <main
                                                                                                                                                                                      style={{
                                                                                                                                                                                              minHeight: "100vh",
                                                                                                                                                                                                      padding: "40px 20px",
                                                                                                                                                                                                              fontFamily: "Arial, sans-serif",
                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                        >
                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                maxWidth: "700px",
                                                                                                                                                                                                                                                          margin: "0 auto",
                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                <h1>Kacung AI</h1>

                                                                                                                                                                                                                                                                                        <p>Chat dengan AI menggunakan Gemini.</p>

                                                                                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                                                                                          value={message}
                                                                                                                                                                                                                                                                                                                    onChange={(e) => setMessage(e.target.value)}
                                                                                                                                                                                                                                                                                                                              placeholder="Tulis pesan kamu..."
                                                                                                                                                                                                                                                                                                                                        rows={5}
                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                              width: "100%",
                                                                                                                                                                                                                                                                                                                                                                          padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                  boxSizing: "border-box",
                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={sendMessage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading || !message.trim()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginTop: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "12px 20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? "Kacung AI sedang berpikir..." : "Kirim"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {reply && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginTop: "25px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "1px solid #ddd",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  whiteSpace: "pre-wrap",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <strong>Kacung AI:</strong>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>{reply}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }